theme: jekyll-theme-hacker
title: Paperbreak
description: Research Paper Breakdowns
permalink: /:year/:month/:day/:title/
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge